apiVersion: apps/v1
kind: Deployment
metadata:
  name: liatrio-dora-api
  labels:
    app: liatrio-dora-api
  annotations:
    reloader.stakater.com/auto: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liatrio-dora-api
  template:
    metadata:
      labels:
        app: liatrio-dora-api
    spec:
      imagePullSecrets:
        - name: ghcr-token
      containers:
        - name: liatrio-dora-api
          image: ghcr.io/liatrio/liatrio-dora-api:latest
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - secretRef:
                name: dora-api-secrets
          env:
            - name: PORT
              value: "3000"
            - name: OTEL_SERVICE_NAME
              value: "liatrio-dora-api"
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://otelcol-collector:4318"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.namespace=tag-devex"
            - name: PRODUCTION_ENVIRONMENT_NAMES
              value: "prod,production,tag-o11y,dev,development"
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 2
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
---
apiVersion: v1
kind: Service
metadata:
  name: liatrio-dora-api
  labels:
    app: liatrio-dora-api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: liatrio-dora-api
