kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-dora-api-ingress
spec:
  podSelector:
    matchLabels:
      app: liatrio-dora-api
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-system
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kyverno