apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dora-api-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: backstage-foundations-kv-prod
    kind: ClusterSecretStore
  target:
    name: dora-api-secrets
  data:
    - secretKey: LOKI_URL
      remoteRef:
        key: dora-api-secrets
        property: LOKI_URL
    - secretKey: LOKI_USER
      remoteRef:
        key: dora-api-secrets
        property: LOKI_USER
    #this should be auto-rotated at some point
    - secretKey: LOKI_TOKEN
      remoteRef:
        key: dora-api-secrets
        property: LOKI_TOKEN
    - secretKey: GITHUB_ORG
      remoteRef:
        key: dora-api-secrets
        property: GITHUB_ORG
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: dora-api-secrets
        property: GITHUB_TOKEN
    - secretKey: LOKI_DAYS_BATCH_SIZE
      remoteRef:
        key: dora-api-secrets
        property: LOKI_DAYS_BATCH_SIZE