name: Build and Deploy Docker Image

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Fetch all tags
        run: git fetch --tags

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate tag
        id: tag
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Find nearest tag
        id: find_tag
        run: |
          tag_name=$(git describe --tags --abbrev=0)
          echo "tag_name=${tag_name}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/liatrio-dora-api:latest
            ghcr.io/${{ github.repository_owner }}/liatrio-dora-api:${{ steps.find_tag.outputs.tag_name }}
            ghcr.io/${{ github.repository_owner }}/liatrio-dora-api:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/liatrio-dora-api:${{ steps.tag.outputs.sha_short }}
