name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate tag
        id: tag
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get release version
        id: release_version
        uses: python-semantic-release/python-semantic-release@master
        with:
          root_options: '-vv --noop'
          push: false
          force: false
          vcs_release: false
          commit: false

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/liatrio-dora-api:latest
            ghcr.io/${{ github.repository_owner }}/liatrio-dora-api:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/liatrio-dora-api:${{ steps.tag.outputs.sha_short }}
            ghcr.io/${{ github.repository_owner }}/liatrio-dora-api:${{ steps.release_version.outputs.version }}
