name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Docker
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Build.Dockerfile
          push: false
          tags: build-liatrio-dora-api:latest

      - name: Run Docker Container
        run: docker run --rm -v ${{ github.workspace }}:/app build-liatrio-dora-api:latest

      - name: Upload built binary as artifact
        uses: actions/upload-artifact@v2
        with:
          name: liatrio-dora-api
          path: target/x86_64-unknown-linux-musl/release/liatrio-dora-api

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download built binary
        uses: actions/download-artifact@v2
        with:
          name: liatrio-dora-api
          path: .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/liatrio-dora-api:latest
