name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config libssl-dev musl-tools

      - name: Install musl OpenSSL development headers
        run: |
          mkdir -p /tmp/local/musl/include/openssl
          mkdir -p /tmp/local/musl/lib
          cp -r /usr/include/openssl/* /tmp/local/musl/include/openssl/
          cp /usr/lib/x86_64-linux-gnu/libssl.a /tmp/local/musl/lib/
          cp /usr/lib/x86_64-linux-gnu/libcrypto.a /tmp/local/musl/lib/

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          profile: minimal
          override: true

      - name: Build the Rust application
        env:
          OPENSSL_DIR: "/tmp/local/musl"
          OPENSSL_INCLUDE_DIR: "/tmp/local/musl/include"
          PKG_CONFIG_ALLOW_CROSS: "1"
        run: |
          rustup target add x86_64-unknown-linux-musl
          cargo build --release --target x86_64-unknown-linux-musl

      - name: Upload built binary as artifact
        uses: actions/upload-artifact@v2
        with:
          name: liatrio-dora-api
          path: target/x86_64-unknown-linux-musl/release/liatrio-dora-api

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download built binary
        uses: actions/download-artifact@v2
        with:
          name: liatrio-dora-api
          path: .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/liatrio-dora-api:latest
